name: .NET Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore dotnet/DopeGrid.Tests/DopeGrid.Tests.csproj

    - name: Build
      run: dotnet build dotnet/DopeGrid.Tests/DopeGrid.Tests.csproj --no-restore --configuration Release

    - name: Test
      run: dotnet test dotnet/DopeGrid.Tests/DopeGrid.Tests.csproj --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage"

    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      if: always()
      with:
        files: '**/coverage.cobertura.xml'
        fail_ci_if_error: false
